#+TITLE: Not a Real Tachistoscope

But lot easier to come by and hopefully just as fun.

[[https://tgetgood.github.io/tachi][Try the demo]] and see for yourself!

* What am I looking at?
  A game that I hope will be fun. A game where you learn to see things faster
  and more dynamically.

  The difficulty autotunes based on your performace.

  I like games where you succeed by growing. Not the fictional character you
  play, but you yourself.
* Where does it come from?
  Inspired by the work of [[https://en.wikipedia.org/wiki/Samuel_Renshaw][Sam Renshaw]] before, during, and after WWII. See also
  [[https://www.tandfonline.com/doi/abs/10.1080/00223980.1945.9917254][this paper]].

  Adapted to modern screens with much lower reliablity than Renshaw's
  tachistoscopes (he trained some students to recognise a 7 digit number in only
  3μs and claimed that almost anyone could be trained to recognise one in
  0.5ms), but I'm hoping there will still be some advantage to memory,
  perception, and visual comprehension to be had with the 1/15 to 1/100 of a
  second duration that can be achieved on modern screens.
* Limitations
  Due to a deep stack that I'm not going to pretend I understand in depth, it
  has proven impossible to reliably show an image for a single frame in a
  browser.

  It seems that setting the minimum time to 4 frames results in images showing
  every time without significant tearing, but obviously this hasn't been tested
  extensively.
* Experimental Mechanics
  The reason I started to write this was to see if I could train myself to widen
  my perceptual field. And to test Renshaw's claims re reading comprehension
  benefits from this kind of training. So with that in mind, let's think about
  the structure of levels.

  While playing this, my overwhelming impression is of being thrashed
  around. It's kind of fun, but lots of variables are beings changed under the
  hood and I have limited control or insight into control them. That's pretty
  bad considering I wrote the code last week.

  The individual ideas: longer numbers, decreasing exposure times, multiple
  images, randomised locations, etc. are still good ideas, I believe, but I need
  to isolate them from one another at first and bring them together later on.

  What's the shortest exposure time for which I can reliably memorise an N digit
  number? That's a useful metric.

  Keeping score boards: you should be able to see your own stats. That requires
  keeping them. Local storage is good enough to start.

  As we start to show multiple numbers, start with columns, but they lay them
  out randomly in a disk of growing size. Or better a thin ring of growing
  diameters. This will make the entire level an exercise in perceptual field
  radius and let us measure the minimum exposure time at various radii to
  memorise. Simplest would be to evenly spread the numbers on a circle but
  randomise the orientation of the circle (but keep the numbers upright).

* Difficulty Levels
  It's a game after all, so how do we make it harder as you go?
** Ideas
*** Length of number to memorise
    This is currently implemented, and for the life of me I can't get the 7
    digit numbers in 4 frames.
*** Length of exposure
    If you can't memorise a given number size, we should show you numbers of
    that size for a longer duration and then work to shorten that duration.
*** Radomise location of text
    If you don't know where the image will pop up it requires a more gestalt
    approach to seeing, which is the point. Will help improve size of perceptual
    field.

    Will this make a difference on a small screen?

    Do we move the numbers each time you get it right, or every retry as well?
    Is that something that should scale with difficulty?
*** Play with delay before flash
    Randomised delay prevents you from priming yourself. I think that's
    important, but I have no evidence as of yet.
*** Multiple numbers
    Show columns of numbers to memorise. Or to really be a jerk just put N
    numbers at random points on the screen.
*** The Element of Scorched Earth
    Add chaff to the mix. Put words or nonsense letters on the screen but you
    only need to memorise the numbers. This might just be frustrating.
*** Text
    Words, short sentences, even whole paragraphs with longer time lapse. The
    problem longer text with this is that we need comprehension tests since pure
    regurgitation isn't what anyone wants.

    What about nonsense text (jaberwock)? Garbage text (qweoasdafht)? You could
    probably publish a cool paper about memory profiles of real language vs
    syntactically/phonetically correct nonsense vs noise text. I don't know if
    it would be any fun for players though.
*** Image matching
    Show 4+ images and make the player figure out which are the same. They can
    creep together like Pavlov's circle & elipse if I feel sadistic.
*** Bird watching
    What bird did you just see? How many? which way were they going?

    Basically replicated Renshaw's work for the navy during WWII, but with
    birds.

    I think this would be fun and useful, but I'll need to find and label the
    images.
