name: Deploy master to GitHub pages as a demo

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'demo'
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: demo
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          npm install
          npm run build
      - name: setup GH pages
        uses: actions/configure-pages@v3
      - name: upload demo
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: deploy demo to GH pages
        id: deployment
        uses: actions/deploy-pages@v1
